create schema Clube_do_livro;

create table LIVROS(
ID_LIVRO INT NOT NULL,
NOME_LIVRO VARCHAR(100) NOT NULL,
AUTORIA VARCHAR(100) NOT NULL,
EDITORA VARCHAR(100) NOT NULL,
CATEGORIA VARCHAR(100) NOT NULL,
PRECO DECIMAL(5,2) NOT NULL,

PRIMARY KEY(ID_LIVRO)
);

create table VENDEDORES(
ID_VENDEDOR INT NOT NULL,
NOME_VENDEDOR VARCHAR(100) NOT NULL,
PRIMARY KEY (ID_VENDEDOR)
);



ALTER TABLE ESTOQUE ADD constraint CE_ESTOQUE_LIVROS
foreign key (ID_LIVRO)
references LIVRO(ID_LIVRO)
ON DELETE ON ACTION
ON UPDATE ON ACTION;